### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by monacofj** [SOII-2016/sevensh#4]
Perhaps missing config.mk and test.mk in repository?

```
$ make
Makefile:42: config.mk: No such file or directory
cc: fatal error: no input files
compilation terminated.
make: *** No rule to make target `config.mk'.  Stop.
```

**Comment by brunoatsantos** [comment]
We only modified the "runcmd.c" file, and we compiled it in "posixeg/exercise/runcmd" directory, using all others files in this directory. 

We received the message "Good, All test OK", yesterday night we had pushed to our repository.

We understood that only 3 files were necessary to include in our repository(runcmd.c; runcmd.h; Makefile), according with this issue > https://github.com/SOII-2016/sevensh/issues/1#issuecomment-217059511

**Comment by monacofj** [comment]
Yes,` runcmd.c ` implementation pass the tests `(`https://github.com/SOII-2016/sevensh/wiki`)`

However, your `libruncm` must build from your own project dir (` posixeg/runcmd/exercise/README `), not from posixeg.  The tests, on the other hand, will be run from `posixeg` by linking to your installed lib.

It seems test.mk is missing in your project dir (`https://github.com/SOII-2016/sevensh/tree/master/runcmd`).

Also, tag part-001 is not in the repository.

I added the missing files in my local copy of sevensh and it compiled ok.  Try to clone a copy in /tmp and test.

**Comment by brunoatsantos** [comment]
We have a problem!!!
When we run the command 'make' or 'make install' to create the lib, we receive:

**gcc  -c  runcmd.c -o runcmd.o
runcmd.c:37:20: fatal error: runcmd.h: No such file or directory
 #include <runcmd.h>
                    ^
compilation terminated.
make: *** [runcmd.o] Error 1**

How can we solve this problem?

Also, We created the tag "part-001" with our latest code.

**Comment by monacofj** [comment]
Please see the pull request for "Add . to include path"
